export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAIL = "PAYMENT_FAIL";

export const CREDIT_ORDER_REQUEST = "CREDIT_ORDER_REQUEST";
export const CREDIT_ORDER_SUCCESS = "CREDIT_ORDER_SUCCESS";
export const CREDIT_ORDER_FAIL = "CREDIT_ORDER_FAIL";

